"""Initial tables

Revision ID: d9f03cf67452
Revises: 
Create Date: 2026-02-19 12:43:54.340919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9f03cf67452'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_routes',
    sa.Column('path', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('is_active', mysql.TINYINT(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', mysql.TINYINT(), server_default='1', nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('balance >= 0', name='check_accounts_balance_positive'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_accounts_service_id'), 'accounts', ['service_id'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('service_route_links',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['service_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'route_id')
    )
    op.create_index('idx_service_route_links_unique', 'service_route_links', ['service_id', 'route_id'], unique=True)
    op.create_table('user_service_links',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'service_id')
    )
    op.create_index('idx_user_service_links_unique', 'user_service_links', ['user_id', 'service_id'], unique=True)
    op.create_table('account_credentials',
    sa.Column('type', sa.Enum('ACCESS_KEY', 'SECRET_KEY', 'API_KEY', 'OAUTH_TOKEN', 'COOKIES', 'USER_ID', 'GOOGLE_CREDENTIALS', name='accountcredentialstype', native_enum=False), nullable=False),
    sa.Column('storage', sa.Enum('INLINE', 'OBJECT', name='accountcredentialstoragetype', native_enum=False), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_credentials_account_id'), 'account_credentials', ['account_id'], unique=False)
    op.create_table('user_generations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'UPLOADING', name='usergenerationstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_generations_account_id'), 'user_generations', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_generations_service_id'), 'user_generations', ['service_id'], unique=False)
    op.create_index(op.f('ix_user_generations_user_id'), 'user_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_generations_user_id'), table_name='user_generations')
    op.drop_index(op.f('ix_user_generations_service_id'), table_name='user_generations')
    op.drop_index(op.f('ix_user_generations_account_id'), table_name='user_generations')
    op.drop_table('user_generations')
    op.drop_index(op.f('ix_account_credentials_account_id'), table_name='account_credentials')
    op.drop_table('account_credentials')
    op.drop_index('idx_user_service_links_unique', table_name='user_service_links')
    op.drop_table('user_service_links')
    op.drop_index('idx_service_route_links_unique', table_name='service_route_links')
    op.drop_table('service_route_links')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_service_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('service_routes')
    # ### end Alembic commands ###
